<?php

namespace Tim\ExampleBundle\Repository;

/**
 * BoatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoatRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListByIds($ids)
    {
        $qb = $this->createQueryBuilder('b');

        $qb->andWhere('b.id IN (:ids)')
            ->setParameter('ids', $ids)
        ;

        return $qb;
    }
}
