<?php

namespace Tim\ExampleBundle\Repository;

/**
 * BoatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoatRepository extends \Doctrine\ORM\EntityRepository
{
}
