<?php

namespace Tim\ExampleBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList()
    {
        $qb = $this->createQueryBuilder('b');

        $qb->orderBy('b.id', 'DESC');

        return $qb;
    }

    public function getListPartialForExample()
    {
        $qb = $this->createQueryBuilder('b');

        $qb->select('partial b.{id, priceTax}');

        $qb->orderBy('b.id', 'DESC');

        return $qb;
    }

    public function getListWithParameters($limit)
    {
        $qb = $this->getList();

        $qb->setMaxResults($limit);

        return $qb;
    }
}
