<?php

namespace Tim\ExampleBundle\Repository;

/**
 * DiscountsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountsRepository extends \Doctrine\ORM\EntityRepository
{
}
