<?php

namespace Tim\ExampleBundle\Repository;

/**
 * OrdersDiscountExtraFieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersDiscountExtraFieldsRepository extends \Doctrine\ORM\EntityRepository
{
}
