<?php

namespace Tim\ExampleBundle\Repository;

/**
 * PlanetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanetRepository extends \Doctrine\ORM\EntityRepository
{
}
