<?php

namespace Tim\CheatSheetBundle\Repository;

/**
 * ApplicationFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationFilesRepository extends \Doctrine\ORM\EntityRepository
{
}
