tim_cheat_sheet_api_v1:
    resource: "@TimCheatSheetBundle/Controller/ApiV1Controller.php"
    type:     rest
    name_prefix: api_v1_
    prefix:   /v1

tim_cheat_sheet_api_v2:
    resource: "@TimCheatSheetBundle/Controller/v2/ApiController.php"
    type:     rest
    name_prefix: api_v2_
    prefix:   /v2