parameters:
    logger_database.class: Tim\CheatSheetBundle\Handler\LoggerDatabaseHandler
    security.authentication.success_handler.class: Tim\CheatSheetBundle\Handler\AuthenticationSuccessHandler
    security.authentication.failure_handler.class: Tim\CheatSheetBundle\Handler\AuthenticationFailureHandler
    security.authentication.listener.form.class: Tim\CheatSheetBundle\Security\Firewall\UsernamePasswordFormAuthenticationListener
    tim_cheat_sheet.post.handler.class: Tim\CheatSheetBundle\Handler\PostHandler
    tim_cheat_sheet.post.class: Tim\CheatSheetBundle\Entity\Post
    tim_cheat_sheet.blog.post.handler.class: Tim\CheatSheetBundle\Handler\BlogPostHandler
    tim_cheat_sheet.blog.post.class: Tim\CheatSheetBundle\Entity\BlogPost
    tim_cheat_sheet.tag.handler.class: Tim\CheatSheetBundle\Handler\TagHandler
    tim_cheat_sheet.tag.class: Tim\CheatSheetBundle\Entity\Tag
    tim_cheat_sheet.subscribe.handler.class: Tim\CheatSheetBundle\Handler\SubscribeHandler
    tim_cheat_sheet.subscribe.class: Tim\CheatSheetBundle\Entity\Subscribe

services:
    logger_database:
        class: '%logger_database.class%'
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tim_cheat_sheet.admin.feedback:
        class: Tim\CheatSheetBundle\Admin\FeedbackAdmin
        arguments: [~, Tim\CheatSheetBundle\Entity\Feedback, SonataAdminBundle:CRUD, '@service_container']
        tags:
            - {name: sonata.admin, manager_type: orm, group: 'Feedback', label: Feedback, on_top: true, icon: '<i class="fa fa-envelope"></i>' }
        calls:
            - [ setTranslationDomain, [ messages ] ]

    tim_cheat_sheet.admin.post_type:
        class: Tim\CheatSheetBundle\Admin\PostTypeAdmin
        arguments: [~, Tim\CheatSheetBundle\Entity\PostType, SonataAdminBundle:CRUD, '@service_container']
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: 'Post Type' }
        calls:
            - [ setTranslationDomain, [ messages ] ]

    tim_cheat_sheet.admin.tag:
        class: Tim\CheatSheetBundle\Admin\TagAdmin
        arguments: [~, Tim\CheatSheetBundle\Entity\Tag, SonataAdminBundle:CRUD, '@service_container']
        tags:
            - {name: sonata.admin, manager_type: orm, group: 'Tag', label: Tag, on_top: true, icon: '<i class="fa fa-tags"></i>' }
        calls:
            - [ setTranslationDomain, [ messages ] ]

    tim_cheat_sheet.admin.question:
        class: Tim\CheatSheetBundle\Admin\QuestionAdmin
        arguments: [~, Tim\CheatSheetBundle\Entity\Question, SonataAdminBundle:CRUD, '@service_container']
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Question}
        calls:
            - [ setTranslationDomain, [ messages ] ]

    tim_cheat_sheet.admin.post:
        class: Tim\CheatSheetBundle\Admin\PostAdmin
        arguments: [~, Tim\CheatSheetBundle\Entity\Post, SonataAdminBundle:CRUD, '@service_container']
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Post}
        calls:
            - [ setTranslationDomain, [ messages ] ]

    tim_cheat_sheet.admin.log:
        class: Tim\CheatSheetBundle\Admin\LogAdmin
        arguments: [~, Tim\CheatSheetBundle\Entity\Log, SonataAdminBundle:CRUD, '@service_container']
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Log}
        calls:
            - [ setTranslationDomain, [ messages ] ]

# handlers:
    tim_cheat_sheet.post.handler:
        class: '%tim_cheat_sheet.post.handler.class%'
        arguments: ['@service_container', '@doctrine.orm.entity_manager', '%tim_cheat_sheet.post.class%']

    tim_cheat_sheet.blog.post.handler:
        class: '%tim_cheat_sheet.blog.post.handler.class%'
        arguments: ['@service_container', '@doctrine.orm.entity_manager', '%tim_cheat_sheet.blog.post.class%']

    tim_cheat_sheet.tag.handler:
        class: '%tim_cheat_sheet.tag.handler.class%'
        arguments: ['@service_container', '@doctrine.orm.entity_manager', '%tim_cheat_sheet.tag.class%']

    tim_cheat_sheet.subscribe.handler:
        class: '%tim_cheat_sheet.subscribe.handler.class%'
        arguments: ['@service_container', '@doctrine.orm.entity_manager', '%tim_cheat_sheet.subscribe.class%']

    tim_cheat_sheet.admin.doctrine_post:
        class: Tim\CheatSheetBundle\Admin\DoctrinePostAdmin
        arguments: [~, Tim\CheatSheetBundle\Entity\DoctrinePost, TimCheatSheetBundle:DoctrinePostAdmin, '@service_container']
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Doctrine Post" }

    tim_cheat_sheet.admin.blog_post:
        class: Tim\CheatSheetBundle\Admin\BlogPostAdmin
        arguments: [~, Tim\CheatSheetBundle\Entity\BlogPost, TimCheatSheetBundle:BlogPostAdmin, '@service_container']
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Blog Post', label: "Blog Post", on_top: true, icon: '<i class="fa fa-file-text"></i>' }

    tim_cheat_sheet.form.tinymce_field:
        class: Tim\CheatSheetBundle\Form\TinymceFieldType
        tags:
            - { name: form.type }
