parameters:
    logger_database.class: Tim\CheatSheetBundle\Handler\LoggerDatabaseHandler
    security.authentication.success_handler.class: Tim\CheatSheetBundle\Handler\AuthenticationSuccessHandler
    security.authentication.failure_handler.class: Tim\CheatSheetBundle\Handler\AuthenticationFailureHandler
    security.authentication.listener.form.class: Tim\CheatSheetBundle\Security\Firewall\UsernamePasswordFormAuthenticationListener

services:
    logger_database:
        class: %logger_database.class%
        calls:
            - [ setContainer, [ @service_container ] ]

    tim_cheat_sheet.admin.feedback:
        class: Tim\CheatSheetBundle\Admin\FeedbackAdmin
        arguments: [~, Tim\CheatSheetBundle\Entity\Feedback, SonataAdminBundle:CRUD, @service_container]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Feedback}
        calls:
            - [ setTranslationDomain, [ messages ] ]

    tim_cheat_sheet.admin.post_type:
        class: Tim\CheatSheetBundle\Admin\PostTypeAdmin
        arguments: [~, Tim\CheatSheetBundle\Entity\PostType, SonataAdminBundle:CRUD, @service_container]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: PostType}
        calls:
            - [ setTranslationDomain, [ messages ] ]
