imports:
    - { resource: parameters.yml }
    - { resource: framework.yml }
    - { resource: swiftmailer.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata_fos_core.yml }
    - { resource: twig.yml }
    - { resource: fos_rest.yml }
    - { resource: doctrine.yml }
    - { resource: ivory.yml }
    - { resource: dizda_cloud_backup.yml }
    - { resource: easy_admin.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
#parameters:
#    locale: "%locale%"

sensio_framework_extra:
    view: { annotations: false }
    router: { annotations: true }
    request: { converters: true }

monolog:
    handlers:
        applog:
            type: service
            level: debug
            id: logger_database
    # channels: ["info", "warning", "error", "crit", "alert", "users"]