fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)
    service:
        user_manager: sonata.user.orm.user_manager                      # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

sonata_user:
    security_acl: false
    manager_type: orm

sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        tim_cheat_sheet.block.service.static: ~

sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            VIEW: VIEW
            DELETE: DELETE
            EXPORT: EXPORT
            OPERATOR: OPERATOR
            MASTER: MASTER
    title:      Admin
    #title_logo: bundles/acmedemo/img/fancy_acme_logo.png
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
            - { position: right, type: tim_cheat_sheet.block.service.static }

sonata_notification:
    backend: sonata.notification.backend.runtime