# Swiftmailer Configuration
swiftmailer:
#    default_mailer: default
#    mailers:
#        default:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    port:       "%mailer_port%"
    encryption: "%mailer_encryption%"