# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        google_analytics: "%google_analytics%"
        yandex_metrika: "%yandex_metrika_key%"
    form:
       resources:
           - 'TimExampleBundle:Form/Type:reg.html.twig'