<?php
/**
 * Created by PhpStorm.
 * User: tim
 * Date: 6/9/2016
 * Time: 9:31 PM
 */

namespace Application\Sonata\UserBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList()
    {
        $qb = $this->createQueryBuilder('u');

        $qb->orderBy('u.id', 'DESC');

        return $qb;
    }
}