<?php

namespace Tim\CheatSheetBundle\Entity;

/**
 * DoctrinePostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctrinePostRepository extends \Doctrine\ORM\EntityRepository
{
}
