<?php

namespace Tim\CheatSheetBundle\Entity;

/**
 * DoctrinePostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctrinePostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList($name = null, $isPublic = true, $isDeleted = false, $maxResults = null)
    {
        return $this->getDoctrinePostsQuery($name, $isPublic, $isDeleted, $maxResults);
    }

    public function getListBySlug($slug = null, $isPublic = true, $isDeleted = false, $maxResults = null)
    {
        return $this->getDoctrinePostsBySlugQuery($slug, $isPublic, $isDeleted, $maxResults);
    }

    public function getListBySlugEqualNull($isPublic = true, $isDeleted = false, $maxResults = null)
    {
        return $this->getDoctrinePostsBySlugEqualNullQuery($isPublic, $isDeleted, $maxResults);
    }

    private function getDoctrinePostsBySlugEqualNullQuery($isPublic = true, $isDeleted = false, $maxResults = null)
    {
        $qb = $this->getDoctrinePostsDefaultQuery($isPublic, $isDeleted, $maxResults);

        $qb->andWhere(
            $qb->expr()->orX(
                $qb->expr()->eq('dp.slug', '\'\''),
                $qb->expr()->isNull('dp.slug')
            )
        );

        return $qb;
    }

    private function getDoctrinePostsBySlugQuery($slug, $isPublic = true, $isDeleted = false, $maxResults = null)
    {
        $qb = $this->getDoctrinePostsDefaultQuery($isPublic, $isDeleted, $maxResults);

        if (is_string($slug)) {
            $qb->andWhere('dp.slug = :slug')
                ->setParameter('slug', $slug)
            ;
        }

        return $qb;
    }

    private function getDoctrinePostsQuery($name, $isPublic = true, $isDeleted = false, $maxResults = null)
    {
        $qb = $this->getDoctrinePostsDefaultQuery($isPublic, $isDeleted, $maxResults);

        if (is_string($name)) {
            $qb->andWhere('dp.text = :name')
                ->setParameter('name', $name)
            ;
        }

        return $qb;
    }

    /**
     * @param bool $isPublic
     * @param bool $isDeleted
     * @param null $maxResults
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function getDoctrinePostsDefaultQuery($isPublic = true, $isDeleted = false, $maxResults = null)
    {
        $qb = $this->createQueryBuilder('dp');

        if (is_bool($isDeleted)) {
            $qb->andWhere('dp.isDeleted = :isDeleted')
                ->setParameter('isDeleted', $isDeleted)
            ;
        }

        if (is_bool($isPublic)) {
            $qb->andWhere('dp.isPublic = :isPublic')
                ->setParameter('isPublic', $isPublic)
            ;
        }

        if (is_int($maxResults)) {
            $qb->setMaxResults($maxResults);
        }

        $qb->addOrderBy('dp.orderPosition', 'ASC');
        $qb->addOrderBy('dp.updatedAt', 'DESC');

        return $qb;
    }
}
