<?php

namespace Tim\CheatSheetBundle\Entity;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList($isAnswered = false, $isDeleted = false, $maxResults = null)
    {
        $qb = $this->createQueryBuilder('f');

        if (is_bool($isDeleted)) {
            $qb->andWhere('f.isDeleted = :isDeleted')
                ->setParameter('isDeleted', $isDeleted)
            ;
        }

        if (is_bool($isAnswered)) {
            $qb->andWhere('f.isAnswered = :isAnswered')
                ->setParameter('isAnswered', $isAnswered)
            ;
        }

        if (is_int($maxResults)) {
            $qb->setMaxResults($maxResults);
        }

        $qb->addOrderBy('f.createdAt', 'DESC');

        return $qb;
    }
}
