<?php

namespace Tim\CheatSheetBundle\Entity;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find the latest logs
     */
    public function findLatest()
    {
        $qb = $this->createQueryBuilder('l');
        $qb->addOrderBy('l.id', 'DESC');
        $qb->setMaxResults(200);
        $q = $qb->getQuery();
        return $q->getResult();
    }
}
