<?php

namespace Tim\CheatSheetBundle\Entity;
use Doctrine\ORM\AbstractQuery;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListAsArray()
    {
        $query = $this->createQueryBuilder('q');

        $query->andWhere('q.isPublish = :isPublish')
            ->setParameter('isPublish', true)
            ->addOrderBy('q.createdAt', 'DESC')
        ;

        $data = $query->getQuery()->getResult(AbstractQuery::HYDRATE_ARRAY);
        return count($data) > 0 ? $data : array();
    }
}
