services:
    tim_example.orders.service:
        class: Tim\ExampleBundle\Service\OrdersService
        arguments: ['@doctrine.orm.entity_manager', 'Tim\ExampleBundle\Entity\Orders']

    tim_example.book.service:
        class: Tim\ExampleBundle\Service\BookService
        arguments: ['@doctrine.orm.entity_manager', 'Tim\ExampleBundle\Entity\Book']

    tim_example.subscriber.created_at:
        class: Tim\ExampleBundle\EventListener\CreatedAtSubscriber
        tags:
        - { name: doctrine.event_subscriber, connection: default }

    tim_example.subscriber.logger:
        class: Tim\ExampleBundle\EventListener\LoggerSubscriber
        tags:
        - { name: doctrine.event_subscriber, connection: default }